/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package fr.abes;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LigneKbartImprime extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4106167831305372180L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LigneKbartImprime\",\"namespace\":\"fr.abes\",\"fields\":[{\"name\":\"currentLine\",\"type\":\"int\"},{\"name\":\"totalLines\",\"type\":\"int\"},{\"name\":\"ppn\",\"type\":\"string\"},{\"name\":\"publicationTitle\",\"type\":[\"null\",\"string\"]},{\"name\":\"printIdentifier\",\"type\":[\"null\",\"string\"]},{\"name\":\"onlineIdentifier\",\"type\":[\"null\",\"string\"]},{\"name\":\"dateFirstIssueOnline\",\"type\":[\"null\",\"string\"]},{\"name\":\"numFirstVolOnline\",\"type\":[\"null\",\"int\"]},{\"name\":\"numFirstIssueOnline\",\"type\":[\"null\",\"int\"]},{\"name\":\"dateLastIssueOnline\",\"type\":[\"null\",\"string\"]},{\"name\":\"numLastVolOnline\",\"type\":[\"null\",\"int\"]},{\"name\":\"numLastIssueOnline\",\"type\":[\"null\",\"int\"]},{\"name\":\"titleUrl\",\"type\":[\"null\",\"string\"]},{\"name\":\"firstAuthor\",\"type\":[\"null\",\"string\"]},{\"name\":\"titleId\",\"type\":[\"null\",\"string\"]},{\"name\":\"embargoInfo\",\"type\":[\"null\",\"string\"]},{\"name\":\"coverageDepth\",\"type\":[\"null\",\"string\"]},{\"name\":\"notes\",\"type\":[\"null\",\"string\"]},{\"name\":\"publisherName\",\"type\":[\"null\",\"string\"]},{\"name\":\"publicationType\",\"type\":[\"null\",\"string\"]},{\"name\":\"dateMonographPublishedPrint\",\"type\":[\"null\",\"string\"]},{\"name\":\"dateMonographPublishedOnline\",\"type\":[\"null\",\"string\"]},{\"name\":\"monographVolume\",\"type\":[\"null\",\"int\"]},{\"name\":\"monographEdition\",\"type\":[\"null\",\"string\"]},{\"name\":\"firstEditor\",\"type\":[\"null\",\"string\"]},{\"name\":\"parentPublicationTitleId\",\"type\":[\"null\",\"string\"]},{\"name\":\"precedingPublicationTitleId\",\"type\":[\"null\",\"string\"]},{\"name\":\"accessType\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LigneKbartImprime> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LigneKbartImprime> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LigneKbartImprime> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LigneKbartImprime> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LigneKbartImprime> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LigneKbartImprime to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LigneKbartImprime from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LigneKbartImprime instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LigneKbartImprime fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int currentLine;
  private int totalLines;
  private java.lang.CharSequence ppn;
  private java.lang.CharSequence publicationTitle;
  private java.lang.CharSequence printIdentifier;
  private java.lang.CharSequence onlineIdentifier;
  private java.lang.CharSequence dateFirstIssueOnline;
  private java.lang.Integer numFirstVolOnline;
  private java.lang.Integer numFirstIssueOnline;
  private java.lang.CharSequence dateLastIssueOnline;
  private java.lang.Integer numLastVolOnline;
  private java.lang.Integer numLastIssueOnline;
  private java.lang.CharSequence titleUrl;
  private java.lang.CharSequence firstAuthor;
  private java.lang.CharSequence titleId;
  private java.lang.CharSequence embargoInfo;
  private java.lang.CharSequence coverageDepth;
  private java.lang.CharSequence notes;
  private java.lang.CharSequence publisherName;
  private java.lang.CharSequence publicationType;
  private java.lang.CharSequence dateMonographPublishedPrint;
  private java.lang.CharSequence dateMonographPublishedOnline;
  private java.lang.Integer monographVolume;
  private java.lang.CharSequence monographEdition;
  private java.lang.CharSequence firstEditor;
  private java.lang.CharSequence parentPublicationTitleId;
  private java.lang.CharSequence precedingPublicationTitleId;
  private java.lang.CharSequence accessType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LigneKbartImprime() {}

  /**
   * All-args constructor.
   * @param currentLine The new value for currentLine
   * @param totalLines The new value for totalLines
   * @param ppn The new value for ppn
   * @param publicationTitle The new value for publicationTitle
   * @param printIdentifier The new value for printIdentifier
   * @param onlineIdentifier The new value for onlineIdentifier
   * @param dateFirstIssueOnline The new value for dateFirstIssueOnline
   * @param numFirstVolOnline The new value for numFirstVolOnline
   * @param numFirstIssueOnline The new value for numFirstIssueOnline
   * @param dateLastIssueOnline The new value for dateLastIssueOnline
   * @param numLastVolOnline The new value for numLastVolOnline
   * @param numLastIssueOnline The new value for numLastIssueOnline
   * @param titleUrl The new value for titleUrl
   * @param firstAuthor The new value for firstAuthor
   * @param titleId The new value for titleId
   * @param embargoInfo The new value for embargoInfo
   * @param coverageDepth The new value for coverageDepth
   * @param notes The new value for notes
   * @param publisherName The new value for publisherName
   * @param publicationType The new value for publicationType
   * @param dateMonographPublishedPrint The new value for dateMonographPublishedPrint
   * @param dateMonographPublishedOnline The new value for dateMonographPublishedOnline
   * @param monographVolume The new value for monographVolume
   * @param monographEdition The new value for monographEdition
   * @param firstEditor The new value for firstEditor
   * @param parentPublicationTitleId The new value for parentPublicationTitleId
   * @param precedingPublicationTitleId The new value for precedingPublicationTitleId
   * @param accessType The new value for accessType
   */
  public LigneKbartImprime(java.lang.Integer currentLine, java.lang.Integer totalLines, java.lang.CharSequence ppn, java.lang.CharSequence publicationTitle, java.lang.CharSequence printIdentifier, java.lang.CharSequence onlineIdentifier, java.lang.CharSequence dateFirstIssueOnline, java.lang.Integer numFirstVolOnline, java.lang.Integer numFirstIssueOnline, java.lang.CharSequence dateLastIssueOnline, java.lang.Integer numLastVolOnline, java.lang.Integer numLastIssueOnline, java.lang.CharSequence titleUrl, java.lang.CharSequence firstAuthor, java.lang.CharSequence titleId, java.lang.CharSequence embargoInfo, java.lang.CharSequence coverageDepth, java.lang.CharSequence notes, java.lang.CharSequence publisherName, java.lang.CharSequence publicationType, java.lang.CharSequence dateMonographPublishedPrint, java.lang.CharSequence dateMonographPublishedOnline, java.lang.Integer monographVolume, java.lang.CharSequence monographEdition, java.lang.CharSequence firstEditor, java.lang.CharSequence parentPublicationTitleId, java.lang.CharSequence precedingPublicationTitleId, java.lang.CharSequence accessType) {
    this.currentLine = currentLine;
    this.totalLines = totalLines;
    this.ppn = ppn;
    this.publicationTitle = publicationTitle;
    this.printIdentifier = printIdentifier;
    this.onlineIdentifier = onlineIdentifier;
    this.dateFirstIssueOnline = dateFirstIssueOnline;
    this.numFirstVolOnline = numFirstVolOnline;
    this.numFirstIssueOnline = numFirstIssueOnline;
    this.dateLastIssueOnline = dateLastIssueOnline;
    this.numLastVolOnline = numLastVolOnline;
    this.numLastIssueOnline = numLastIssueOnline;
    this.titleUrl = titleUrl;
    this.firstAuthor = firstAuthor;
    this.titleId = titleId;
    this.embargoInfo = embargoInfo;
    this.coverageDepth = coverageDepth;
    this.notes = notes;
    this.publisherName = publisherName;
    this.publicationType = publicationType;
    this.dateMonographPublishedPrint = dateMonographPublishedPrint;
    this.dateMonographPublishedOnline = dateMonographPublishedOnline;
    this.monographVolume = monographVolume;
    this.monographEdition = monographEdition;
    this.firstEditor = firstEditor;
    this.parentPublicationTitleId = parentPublicationTitleId;
    this.precedingPublicationTitleId = precedingPublicationTitleId;
    this.accessType = accessType;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return currentLine;
    case 1: return totalLines;
    case 2: return ppn;
    case 3: return publicationTitle;
    case 4: return printIdentifier;
    case 5: return onlineIdentifier;
    case 6: return dateFirstIssueOnline;
    case 7: return numFirstVolOnline;
    case 8: return numFirstIssueOnline;
    case 9: return dateLastIssueOnline;
    case 10: return numLastVolOnline;
    case 11: return numLastIssueOnline;
    case 12: return titleUrl;
    case 13: return firstAuthor;
    case 14: return titleId;
    case 15: return embargoInfo;
    case 16: return coverageDepth;
    case 17: return notes;
    case 18: return publisherName;
    case 19: return publicationType;
    case 20: return dateMonographPublishedPrint;
    case 21: return dateMonographPublishedOnline;
    case 22: return monographVolume;
    case 23: return monographEdition;
    case 24: return firstEditor;
    case 25: return parentPublicationTitleId;
    case 26: return precedingPublicationTitleId;
    case 27: return accessType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: currentLine = (java.lang.Integer)value$; break;
    case 1: totalLines = (java.lang.Integer)value$; break;
    case 2: ppn = (java.lang.CharSequence)value$; break;
    case 3: publicationTitle = (java.lang.CharSequence)value$; break;
    case 4: printIdentifier = (java.lang.CharSequence)value$; break;
    case 5: onlineIdentifier = (java.lang.CharSequence)value$; break;
    case 6: dateFirstIssueOnline = (java.lang.CharSequence)value$; break;
    case 7: numFirstVolOnline = (java.lang.Integer)value$; break;
    case 8: numFirstIssueOnline = (java.lang.Integer)value$; break;
    case 9: dateLastIssueOnline = (java.lang.CharSequence)value$; break;
    case 10: numLastVolOnline = (java.lang.Integer)value$; break;
    case 11: numLastIssueOnline = (java.lang.Integer)value$; break;
    case 12: titleUrl = (java.lang.CharSequence)value$; break;
    case 13: firstAuthor = (java.lang.CharSequence)value$; break;
    case 14: titleId = (java.lang.CharSequence)value$; break;
    case 15: embargoInfo = (java.lang.CharSequence)value$; break;
    case 16: coverageDepth = (java.lang.CharSequence)value$; break;
    case 17: notes = (java.lang.CharSequence)value$; break;
    case 18: publisherName = (java.lang.CharSequence)value$; break;
    case 19: publicationType = (java.lang.CharSequence)value$; break;
    case 20: dateMonographPublishedPrint = (java.lang.CharSequence)value$; break;
    case 21: dateMonographPublishedOnline = (java.lang.CharSequence)value$; break;
    case 22: monographVolume = (java.lang.Integer)value$; break;
    case 23: monographEdition = (java.lang.CharSequence)value$; break;
    case 24: firstEditor = (java.lang.CharSequence)value$; break;
    case 25: parentPublicationTitleId = (java.lang.CharSequence)value$; break;
    case 26: precedingPublicationTitleId = (java.lang.CharSequence)value$; break;
    case 27: accessType = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'currentLine' field.
   * @return The value of the 'currentLine' field.
   */
  public int getCurrentLine() {
    return currentLine;
  }


  /**
   * Sets the value of the 'currentLine' field.
   * @param value the value to set.
   */
  public void setCurrentLine(int value) {
    this.currentLine = value;
  }

  /**
   * Gets the value of the 'totalLines' field.
   * @return The value of the 'totalLines' field.
   */
  public int getTotalLines() {
    return totalLines;
  }


  /**
   * Sets the value of the 'totalLines' field.
   * @param value the value to set.
   */
  public void setTotalLines(int value) {
    this.totalLines = value;
  }

  /**
   * Gets the value of the 'ppn' field.
   * @return The value of the 'ppn' field.
   */
  public java.lang.CharSequence getPpn() {
    return ppn;
  }


  /**
   * Sets the value of the 'ppn' field.
   * @param value the value to set.
   */
  public void setPpn(java.lang.CharSequence value) {
    this.ppn = value;
  }

  /**
   * Gets the value of the 'publicationTitle' field.
   * @return The value of the 'publicationTitle' field.
   */
  public java.lang.CharSequence getPublicationTitle() {
    return publicationTitle;
  }


  /**
   * Sets the value of the 'publicationTitle' field.
   * @param value the value to set.
   */
  public void setPublicationTitle(java.lang.CharSequence value) {
    this.publicationTitle = value;
  }

  /**
   * Gets the value of the 'printIdentifier' field.
   * @return The value of the 'printIdentifier' field.
   */
  public java.lang.CharSequence getPrintIdentifier() {
    return printIdentifier;
  }


  /**
   * Sets the value of the 'printIdentifier' field.
   * @param value the value to set.
   */
  public void setPrintIdentifier(java.lang.CharSequence value) {
    this.printIdentifier = value;
  }

  /**
   * Gets the value of the 'onlineIdentifier' field.
   * @return The value of the 'onlineIdentifier' field.
   */
  public java.lang.CharSequence getOnlineIdentifier() {
    return onlineIdentifier;
  }


  /**
   * Sets the value of the 'onlineIdentifier' field.
   * @param value the value to set.
   */
  public void setOnlineIdentifier(java.lang.CharSequence value) {
    this.onlineIdentifier = value;
  }

  /**
   * Gets the value of the 'dateFirstIssueOnline' field.
   * @return The value of the 'dateFirstIssueOnline' field.
   */
  public java.lang.CharSequence getDateFirstIssueOnline() {
    return dateFirstIssueOnline;
  }


  /**
   * Sets the value of the 'dateFirstIssueOnline' field.
   * @param value the value to set.
   */
  public void setDateFirstIssueOnline(java.lang.CharSequence value) {
    this.dateFirstIssueOnline = value;
  }

  /**
   * Gets the value of the 'numFirstVolOnline' field.
   * @return The value of the 'numFirstVolOnline' field.
   */
  public java.lang.Integer getNumFirstVolOnline() {
    return numFirstVolOnline;
  }


  /**
   * Sets the value of the 'numFirstVolOnline' field.
   * @param value the value to set.
   */
  public void setNumFirstVolOnline(java.lang.Integer value) {
    this.numFirstVolOnline = value;
  }

  /**
   * Gets the value of the 'numFirstIssueOnline' field.
   * @return The value of the 'numFirstIssueOnline' field.
   */
  public java.lang.Integer getNumFirstIssueOnline() {
    return numFirstIssueOnline;
  }


  /**
   * Sets the value of the 'numFirstIssueOnline' field.
   * @param value the value to set.
   */
  public void setNumFirstIssueOnline(java.lang.Integer value) {
    this.numFirstIssueOnline = value;
  }

  /**
   * Gets the value of the 'dateLastIssueOnline' field.
   * @return The value of the 'dateLastIssueOnline' field.
   */
  public java.lang.CharSequence getDateLastIssueOnline() {
    return dateLastIssueOnline;
  }


  /**
   * Sets the value of the 'dateLastIssueOnline' field.
   * @param value the value to set.
   */
  public void setDateLastIssueOnline(java.lang.CharSequence value) {
    this.dateLastIssueOnline = value;
  }

  /**
   * Gets the value of the 'numLastVolOnline' field.
   * @return The value of the 'numLastVolOnline' field.
   */
  public java.lang.Integer getNumLastVolOnline() {
    return numLastVolOnline;
  }


  /**
   * Sets the value of the 'numLastVolOnline' field.
   * @param value the value to set.
   */
  public void setNumLastVolOnline(java.lang.Integer value) {
    this.numLastVolOnline = value;
  }

  /**
   * Gets the value of the 'numLastIssueOnline' field.
   * @return The value of the 'numLastIssueOnline' field.
   */
  public java.lang.Integer getNumLastIssueOnline() {
    return numLastIssueOnline;
  }


  /**
   * Sets the value of the 'numLastIssueOnline' field.
   * @param value the value to set.
   */
  public void setNumLastIssueOnline(java.lang.Integer value) {
    this.numLastIssueOnline = value;
  }

  /**
   * Gets the value of the 'titleUrl' field.
   * @return The value of the 'titleUrl' field.
   */
  public java.lang.CharSequence getTitleUrl() {
    return titleUrl;
  }


  /**
   * Sets the value of the 'titleUrl' field.
   * @param value the value to set.
   */
  public void setTitleUrl(java.lang.CharSequence value) {
    this.titleUrl = value;
  }

  /**
   * Gets the value of the 'firstAuthor' field.
   * @return The value of the 'firstAuthor' field.
   */
  public java.lang.CharSequence getFirstAuthor() {
    return firstAuthor;
  }


  /**
   * Sets the value of the 'firstAuthor' field.
   * @param value the value to set.
   */
  public void setFirstAuthor(java.lang.CharSequence value) {
    this.firstAuthor = value;
  }

  /**
   * Gets the value of the 'titleId' field.
   * @return The value of the 'titleId' field.
   */
  public java.lang.CharSequence getTitleId() {
    return titleId;
  }


  /**
   * Sets the value of the 'titleId' field.
   * @param value the value to set.
   */
  public void setTitleId(java.lang.CharSequence value) {
    this.titleId = value;
  }

  /**
   * Gets the value of the 'embargoInfo' field.
   * @return The value of the 'embargoInfo' field.
   */
  public java.lang.CharSequence getEmbargoInfo() {
    return embargoInfo;
  }


  /**
   * Sets the value of the 'embargoInfo' field.
   * @param value the value to set.
   */
  public void setEmbargoInfo(java.lang.CharSequence value) {
    this.embargoInfo = value;
  }

  /**
   * Gets the value of the 'coverageDepth' field.
   * @return The value of the 'coverageDepth' field.
   */
  public java.lang.CharSequence getCoverageDepth() {
    return coverageDepth;
  }


  /**
   * Sets the value of the 'coverageDepth' field.
   * @param value the value to set.
   */
  public void setCoverageDepth(java.lang.CharSequence value) {
    this.coverageDepth = value;
  }

  /**
   * Gets the value of the 'notes' field.
   * @return The value of the 'notes' field.
   */
  public java.lang.CharSequence getNotes() {
    return notes;
  }


  /**
   * Sets the value of the 'notes' field.
   * @param value the value to set.
   */
  public void setNotes(java.lang.CharSequence value) {
    this.notes = value;
  }

  /**
   * Gets the value of the 'publisherName' field.
   * @return The value of the 'publisherName' field.
   */
  public java.lang.CharSequence getPublisherName() {
    return publisherName;
  }


  /**
   * Sets the value of the 'publisherName' field.
   * @param value the value to set.
   */
  public void setPublisherName(java.lang.CharSequence value) {
    this.publisherName = value;
  }

  /**
   * Gets the value of the 'publicationType' field.
   * @return The value of the 'publicationType' field.
   */
  public java.lang.CharSequence getPublicationType() {
    return publicationType;
  }


  /**
   * Sets the value of the 'publicationType' field.
   * @param value the value to set.
   */
  public void setPublicationType(java.lang.CharSequence value) {
    this.publicationType = value;
  }

  /**
   * Gets the value of the 'dateMonographPublishedPrint' field.
   * @return The value of the 'dateMonographPublishedPrint' field.
   */
  public java.lang.CharSequence getDateMonographPublishedPrint() {
    return dateMonographPublishedPrint;
  }


  /**
   * Sets the value of the 'dateMonographPublishedPrint' field.
   * @param value the value to set.
   */
  public void setDateMonographPublishedPrint(java.lang.CharSequence value) {
    this.dateMonographPublishedPrint = value;
  }

  /**
   * Gets the value of the 'dateMonographPublishedOnline' field.
   * @return The value of the 'dateMonographPublishedOnline' field.
   */
  public java.lang.CharSequence getDateMonographPublishedOnline() {
    return dateMonographPublishedOnline;
  }


  /**
   * Sets the value of the 'dateMonographPublishedOnline' field.
   * @param value the value to set.
   */
  public void setDateMonographPublishedOnline(java.lang.CharSequence value) {
    this.dateMonographPublishedOnline = value;
  }

  /**
   * Gets the value of the 'monographVolume' field.
   * @return The value of the 'monographVolume' field.
   */
  public java.lang.Integer getMonographVolume() {
    return monographVolume;
  }


  /**
   * Sets the value of the 'monographVolume' field.
   * @param value the value to set.
   */
  public void setMonographVolume(java.lang.Integer value) {
    this.monographVolume = value;
  }

  /**
   * Gets the value of the 'monographEdition' field.
   * @return The value of the 'monographEdition' field.
   */
  public java.lang.CharSequence getMonographEdition() {
    return monographEdition;
  }


  /**
   * Sets the value of the 'monographEdition' field.
   * @param value the value to set.
   */
  public void setMonographEdition(java.lang.CharSequence value) {
    this.monographEdition = value;
  }

  /**
   * Gets the value of the 'firstEditor' field.
   * @return The value of the 'firstEditor' field.
   */
  public java.lang.CharSequence getFirstEditor() {
    return firstEditor;
  }


  /**
   * Sets the value of the 'firstEditor' field.
   * @param value the value to set.
   */
  public void setFirstEditor(java.lang.CharSequence value) {
    this.firstEditor = value;
  }

  /**
   * Gets the value of the 'parentPublicationTitleId' field.
   * @return The value of the 'parentPublicationTitleId' field.
   */
  public java.lang.CharSequence getParentPublicationTitleId() {
    return parentPublicationTitleId;
  }


  /**
   * Sets the value of the 'parentPublicationTitleId' field.
   * @param value the value to set.
   */
  public void setParentPublicationTitleId(java.lang.CharSequence value) {
    this.parentPublicationTitleId = value;
  }

  /**
   * Gets the value of the 'precedingPublicationTitleId' field.
   * @return The value of the 'precedingPublicationTitleId' field.
   */
  public java.lang.CharSequence getPrecedingPublicationTitleId() {
    return precedingPublicationTitleId;
  }


  /**
   * Sets the value of the 'precedingPublicationTitleId' field.
   * @param value the value to set.
   */
  public void setPrecedingPublicationTitleId(java.lang.CharSequence value) {
    this.precedingPublicationTitleId = value;
  }

  /**
   * Gets the value of the 'accessType' field.
   * @return The value of the 'accessType' field.
   */
  public java.lang.CharSequence getAccessType() {
    return accessType;
  }


  /**
   * Sets the value of the 'accessType' field.
   * @param value the value to set.
   */
  public void setAccessType(java.lang.CharSequence value) {
    this.accessType = value;
  }

  /**
   * Creates a new LigneKbartImprime RecordBuilder.
   * @return A new LigneKbartImprime RecordBuilder
   */
  public static fr.abes.LigneKbartImprime.Builder newBuilder() {
    return new fr.abes.LigneKbartImprime.Builder();
  }

  /**
   * Creates a new LigneKbartImprime RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LigneKbartImprime RecordBuilder
   */
  public static fr.abes.LigneKbartImprime.Builder newBuilder(fr.abes.LigneKbartImprime.Builder other) {
    if (other == null) {
      return new fr.abes.LigneKbartImprime.Builder();
    } else {
      return new fr.abes.LigneKbartImprime.Builder(other);
    }
  }

  /**
   * Creates a new LigneKbartImprime RecordBuilder by copying an existing LigneKbartImprime instance.
   * @param other The existing instance to copy.
   * @return A new LigneKbartImprime RecordBuilder
   */
  public static fr.abes.LigneKbartImprime.Builder newBuilder(fr.abes.LigneKbartImprime other) {
    if (other == null) {
      return new fr.abes.LigneKbartImprime.Builder();
    } else {
      return new fr.abes.LigneKbartImprime.Builder(other);
    }
  }

  /**
   * RecordBuilder for LigneKbartImprime instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LigneKbartImprime>
    implements org.apache.avro.data.RecordBuilder<LigneKbartImprime> {

    private int currentLine;
    private int totalLines;
    private java.lang.CharSequence ppn;
    private java.lang.CharSequence publicationTitle;
    private java.lang.CharSequence printIdentifier;
    private java.lang.CharSequence onlineIdentifier;
    private java.lang.CharSequence dateFirstIssueOnline;
    private java.lang.Integer numFirstVolOnline;
    private java.lang.Integer numFirstIssueOnline;
    private java.lang.CharSequence dateLastIssueOnline;
    private java.lang.Integer numLastVolOnline;
    private java.lang.Integer numLastIssueOnline;
    private java.lang.CharSequence titleUrl;
    private java.lang.CharSequence firstAuthor;
    private java.lang.CharSequence titleId;
    private java.lang.CharSequence embargoInfo;
    private java.lang.CharSequence coverageDepth;
    private java.lang.CharSequence notes;
    private java.lang.CharSequence publisherName;
    private java.lang.CharSequence publicationType;
    private java.lang.CharSequence dateMonographPublishedPrint;
    private java.lang.CharSequence dateMonographPublishedOnline;
    private java.lang.Integer monographVolume;
    private java.lang.CharSequence monographEdition;
    private java.lang.CharSequence firstEditor;
    private java.lang.CharSequence parentPublicationTitleId;
    private java.lang.CharSequence precedingPublicationTitleId;
    private java.lang.CharSequence accessType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(fr.abes.LigneKbartImprime.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.currentLine)) {
        this.currentLine = data().deepCopy(fields()[0].schema(), other.currentLine);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.totalLines)) {
        this.totalLines = data().deepCopy(fields()[1].schema(), other.totalLines);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ppn)) {
        this.ppn = data().deepCopy(fields()[2].schema(), other.ppn);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.publicationTitle)) {
        this.publicationTitle = data().deepCopy(fields()[3].schema(), other.publicationTitle);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.printIdentifier)) {
        this.printIdentifier = data().deepCopy(fields()[4].schema(), other.printIdentifier);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.onlineIdentifier)) {
        this.onlineIdentifier = data().deepCopy(fields()[5].schema(), other.onlineIdentifier);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.dateFirstIssueOnline)) {
        this.dateFirstIssueOnline = data().deepCopy(fields()[6].schema(), other.dateFirstIssueOnline);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.numFirstVolOnline)) {
        this.numFirstVolOnline = data().deepCopy(fields()[7].schema(), other.numFirstVolOnline);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.numFirstIssueOnline)) {
        this.numFirstIssueOnline = data().deepCopy(fields()[8].schema(), other.numFirstIssueOnline);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.dateLastIssueOnline)) {
        this.dateLastIssueOnline = data().deepCopy(fields()[9].schema(), other.dateLastIssueOnline);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.numLastVolOnline)) {
        this.numLastVolOnline = data().deepCopy(fields()[10].schema(), other.numLastVolOnline);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.numLastIssueOnline)) {
        this.numLastIssueOnline = data().deepCopy(fields()[11].schema(), other.numLastIssueOnline);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.titleUrl)) {
        this.titleUrl = data().deepCopy(fields()[12].schema(), other.titleUrl);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.firstAuthor)) {
        this.firstAuthor = data().deepCopy(fields()[13].schema(), other.firstAuthor);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.titleId)) {
        this.titleId = data().deepCopy(fields()[14].schema(), other.titleId);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.embargoInfo)) {
        this.embargoInfo = data().deepCopy(fields()[15].schema(), other.embargoInfo);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.coverageDepth)) {
        this.coverageDepth = data().deepCopy(fields()[16].schema(), other.coverageDepth);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.notes)) {
        this.notes = data().deepCopy(fields()[17].schema(), other.notes);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.publisherName)) {
        this.publisherName = data().deepCopy(fields()[18].schema(), other.publisherName);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.publicationType)) {
        this.publicationType = data().deepCopy(fields()[19].schema(), other.publicationType);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.dateMonographPublishedPrint)) {
        this.dateMonographPublishedPrint = data().deepCopy(fields()[20].schema(), other.dateMonographPublishedPrint);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
      if (isValidValue(fields()[21], other.dateMonographPublishedOnline)) {
        this.dateMonographPublishedOnline = data().deepCopy(fields()[21].schema(), other.dateMonographPublishedOnline);
        fieldSetFlags()[21] = other.fieldSetFlags()[21];
      }
      if (isValidValue(fields()[22], other.monographVolume)) {
        this.monographVolume = data().deepCopy(fields()[22].schema(), other.monographVolume);
        fieldSetFlags()[22] = other.fieldSetFlags()[22];
      }
      if (isValidValue(fields()[23], other.monographEdition)) {
        this.monographEdition = data().deepCopy(fields()[23].schema(), other.monographEdition);
        fieldSetFlags()[23] = other.fieldSetFlags()[23];
      }
      if (isValidValue(fields()[24], other.firstEditor)) {
        this.firstEditor = data().deepCopy(fields()[24].schema(), other.firstEditor);
        fieldSetFlags()[24] = other.fieldSetFlags()[24];
      }
      if (isValidValue(fields()[25], other.parentPublicationTitleId)) {
        this.parentPublicationTitleId = data().deepCopy(fields()[25].schema(), other.parentPublicationTitleId);
        fieldSetFlags()[25] = other.fieldSetFlags()[25];
      }
      if (isValidValue(fields()[26], other.precedingPublicationTitleId)) {
        this.precedingPublicationTitleId = data().deepCopy(fields()[26].schema(), other.precedingPublicationTitleId);
        fieldSetFlags()[26] = other.fieldSetFlags()[26];
      }
      if (isValidValue(fields()[27], other.accessType)) {
        this.accessType = data().deepCopy(fields()[27].schema(), other.accessType);
        fieldSetFlags()[27] = other.fieldSetFlags()[27];
      }
    }

    /**
     * Creates a Builder by copying an existing LigneKbartImprime instance
     * @param other The existing instance to copy.
     */
    private Builder(fr.abes.LigneKbartImprime other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.currentLine)) {
        this.currentLine = data().deepCopy(fields()[0].schema(), other.currentLine);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.totalLines)) {
        this.totalLines = data().deepCopy(fields()[1].schema(), other.totalLines);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ppn)) {
        this.ppn = data().deepCopy(fields()[2].schema(), other.ppn);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.publicationTitle)) {
        this.publicationTitle = data().deepCopy(fields()[3].schema(), other.publicationTitle);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.printIdentifier)) {
        this.printIdentifier = data().deepCopy(fields()[4].schema(), other.printIdentifier);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.onlineIdentifier)) {
        this.onlineIdentifier = data().deepCopy(fields()[5].schema(), other.onlineIdentifier);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.dateFirstIssueOnline)) {
        this.dateFirstIssueOnline = data().deepCopy(fields()[6].schema(), other.dateFirstIssueOnline);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.numFirstVolOnline)) {
        this.numFirstVolOnline = data().deepCopy(fields()[7].schema(), other.numFirstVolOnline);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.numFirstIssueOnline)) {
        this.numFirstIssueOnline = data().deepCopy(fields()[8].schema(), other.numFirstIssueOnline);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.dateLastIssueOnline)) {
        this.dateLastIssueOnline = data().deepCopy(fields()[9].schema(), other.dateLastIssueOnline);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.numLastVolOnline)) {
        this.numLastVolOnline = data().deepCopy(fields()[10].schema(), other.numLastVolOnline);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.numLastIssueOnline)) {
        this.numLastIssueOnline = data().deepCopy(fields()[11].schema(), other.numLastIssueOnline);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.titleUrl)) {
        this.titleUrl = data().deepCopy(fields()[12].schema(), other.titleUrl);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.firstAuthor)) {
        this.firstAuthor = data().deepCopy(fields()[13].schema(), other.firstAuthor);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.titleId)) {
        this.titleId = data().deepCopy(fields()[14].schema(), other.titleId);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.embargoInfo)) {
        this.embargoInfo = data().deepCopy(fields()[15].schema(), other.embargoInfo);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.coverageDepth)) {
        this.coverageDepth = data().deepCopy(fields()[16].schema(), other.coverageDepth);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.notes)) {
        this.notes = data().deepCopy(fields()[17].schema(), other.notes);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.publisherName)) {
        this.publisherName = data().deepCopy(fields()[18].schema(), other.publisherName);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.publicationType)) {
        this.publicationType = data().deepCopy(fields()[19].schema(), other.publicationType);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.dateMonographPublishedPrint)) {
        this.dateMonographPublishedPrint = data().deepCopy(fields()[20].schema(), other.dateMonographPublishedPrint);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.dateMonographPublishedOnline)) {
        this.dateMonographPublishedOnline = data().deepCopy(fields()[21].schema(), other.dateMonographPublishedOnline);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.monographVolume)) {
        this.monographVolume = data().deepCopy(fields()[22].schema(), other.monographVolume);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.monographEdition)) {
        this.monographEdition = data().deepCopy(fields()[23].schema(), other.monographEdition);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.firstEditor)) {
        this.firstEditor = data().deepCopy(fields()[24].schema(), other.firstEditor);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.parentPublicationTitleId)) {
        this.parentPublicationTitleId = data().deepCopy(fields()[25].schema(), other.parentPublicationTitleId);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.precedingPublicationTitleId)) {
        this.precedingPublicationTitleId = data().deepCopy(fields()[26].schema(), other.precedingPublicationTitleId);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.accessType)) {
        this.accessType = data().deepCopy(fields()[27].schema(), other.accessType);
        fieldSetFlags()[27] = true;
      }
    }

    /**
      * Gets the value of the 'currentLine' field.
      * @return The value.
      */
    public int getCurrentLine() {
      return currentLine;
    }


    /**
      * Sets the value of the 'currentLine' field.
      * @param value The value of 'currentLine'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setCurrentLine(int value) {
      validate(fields()[0], value);
      this.currentLine = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'currentLine' field has been set.
      * @return True if the 'currentLine' field has been set, false otherwise.
      */
    public boolean hasCurrentLine() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'currentLine' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearCurrentLine() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalLines' field.
      * @return The value.
      */
    public int getTotalLines() {
      return totalLines;
    }


    /**
      * Sets the value of the 'totalLines' field.
      * @param value The value of 'totalLines'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setTotalLines(int value) {
      validate(fields()[1], value);
      this.totalLines = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'totalLines' field has been set.
      * @return True if the 'totalLines' field has been set, false otherwise.
      */
    public boolean hasTotalLines() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'totalLines' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearTotalLines() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ppn' field.
      * @return The value.
      */
    public java.lang.CharSequence getPpn() {
      return ppn;
    }


    /**
      * Sets the value of the 'ppn' field.
      * @param value The value of 'ppn'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setPpn(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ppn = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ppn' field has been set.
      * @return True if the 'ppn' field has been set, false otherwise.
      */
    public boolean hasPpn() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ppn' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearPpn() {
      ppn = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'publicationTitle' field.
      * @return The value.
      */
    public java.lang.CharSequence getPublicationTitle() {
      return publicationTitle;
    }


    /**
      * Sets the value of the 'publicationTitle' field.
      * @param value The value of 'publicationTitle'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setPublicationTitle(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.publicationTitle = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'publicationTitle' field has been set.
      * @return True if the 'publicationTitle' field has been set, false otherwise.
      */
    public boolean hasPublicationTitle() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'publicationTitle' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearPublicationTitle() {
      publicationTitle = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'printIdentifier' field.
      * @return The value.
      */
    public java.lang.CharSequence getPrintIdentifier() {
      return printIdentifier;
    }


    /**
      * Sets the value of the 'printIdentifier' field.
      * @param value The value of 'printIdentifier'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setPrintIdentifier(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.printIdentifier = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'printIdentifier' field has been set.
      * @return True if the 'printIdentifier' field has been set, false otherwise.
      */
    public boolean hasPrintIdentifier() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'printIdentifier' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearPrintIdentifier() {
      printIdentifier = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'onlineIdentifier' field.
      * @return The value.
      */
    public java.lang.CharSequence getOnlineIdentifier() {
      return onlineIdentifier;
    }


    /**
      * Sets the value of the 'onlineIdentifier' field.
      * @param value The value of 'onlineIdentifier'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setOnlineIdentifier(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.onlineIdentifier = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'onlineIdentifier' field has been set.
      * @return True if the 'onlineIdentifier' field has been set, false otherwise.
      */
    public boolean hasOnlineIdentifier() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'onlineIdentifier' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearOnlineIdentifier() {
      onlineIdentifier = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateFirstIssueOnline' field.
      * @return The value.
      */
    public java.lang.CharSequence getDateFirstIssueOnline() {
      return dateFirstIssueOnline;
    }


    /**
      * Sets the value of the 'dateFirstIssueOnline' field.
      * @param value The value of 'dateFirstIssueOnline'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setDateFirstIssueOnline(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.dateFirstIssueOnline = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'dateFirstIssueOnline' field has been set.
      * @return True if the 'dateFirstIssueOnline' field has been set, false otherwise.
      */
    public boolean hasDateFirstIssueOnline() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'dateFirstIssueOnline' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearDateFirstIssueOnline() {
      dateFirstIssueOnline = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'numFirstVolOnline' field.
      * @return The value.
      */
    public java.lang.Integer getNumFirstVolOnline() {
      return numFirstVolOnline;
    }


    /**
      * Sets the value of the 'numFirstVolOnline' field.
      * @param value The value of 'numFirstVolOnline'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setNumFirstVolOnline(java.lang.Integer value) {
      validate(fields()[7], value);
      this.numFirstVolOnline = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'numFirstVolOnline' field has been set.
      * @return True if the 'numFirstVolOnline' field has been set, false otherwise.
      */
    public boolean hasNumFirstVolOnline() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'numFirstVolOnline' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearNumFirstVolOnline() {
      numFirstVolOnline = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'numFirstIssueOnline' field.
      * @return The value.
      */
    public java.lang.Integer getNumFirstIssueOnline() {
      return numFirstIssueOnline;
    }


    /**
      * Sets the value of the 'numFirstIssueOnline' field.
      * @param value The value of 'numFirstIssueOnline'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setNumFirstIssueOnline(java.lang.Integer value) {
      validate(fields()[8], value);
      this.numFirstIssueOnline = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'numFirstIssueOnline' field has been set.
      * @return True if the 'numFirstIssueOnline' field has been set, false otherwise.
      */
    public boolean hasNumFirstIssueOnline() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'numFirstIssueOnline' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearNumFirstIssueOnline() {
      numFirstIssueOnline = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateLastIssueOnline' field.
      * @return The value.
      */
    public java.lang.CharSequence getDateLastIssueOnline() {
      return dateLastIssueOnline;
    }


    /**
      * Sets the value of the 'dateLastIssueOnline' field.
      * @param value The value of 'dateLastIssueOnline'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setDateLastIssueOnline(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.dateLastIssueOnline = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'dateLastIssueOnline' field has been set.
      * @return True if the 'dateLastIssueOnline' field has been set, false otherwise.
      */
    public boolean hasDateLastIssueOnline() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'dateLastIssueOnline' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearDateLastIssueOnline() {
      dateLastIssueOnline = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'numLastVolOnline' field.
      * @return The value.
      */
    public java.lang.Integer getNumLastVolOnline() {
      return numLastVolOnline;
    }


    /**
      * Sets the value of the 'numLastVolOnline' field.
      * @param value The value of 'numLastVolOnline'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setNumLastVolOnline(java.lang.Integer value) {
      validate(fields()[10], value);
      this.numLastVolOnline = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'numLastVolOnline' field has been set.
      * @return True if the 'numLastVolOnline' field has been set, false otherwise.
      */
    public boolean hasNumLastVolOnline() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'numLastVolOnline' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearNumLastVolOnline() {
      numLastVolOnline = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'numLastIssueOnline' field.
      * @return The value.
      */
    public java.lang.Integer getNumLastIssueOnline() {
      return numLastIssueOnline;
    }


    /**
      * Sets the value of the 'numLastIssueOnline' field.
      * @param value The value of 'numLastIssueOnline'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setNumLastIssueOnline(java.lang.Integer value) {
      validate(fields()[11], value);
      this.numLastIssueOnline = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'numLastIssueOnline' field has been set.
      * @return True if the 'numLastIssueOnline' field has been set, false otherwise.
      */
    public boolean hasNumLastIssueOnline() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'numLastIssueOnline' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearNumLastIssueOnline() {
      numLastIssueOnline = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'titleUrl' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitleUrl() {
      return titleUrl;
    }


    /**
      * Sets the value of the 'titleUrl' field.
      * @param value The value of 'titleUrl'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setTitleUrl(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.titleUrl = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'titleUrl' field has been set.
      * @return True if the 'titleUrl' field has been set, false otherwise.
      */
    public boolean hasTitleUrl() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'titleUrl' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearTitleUrl() {
      titleUrl = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstAuthor' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstAuthor() {
      return firstAuthor;
    }


    /**
      * Sets the value of the 'firstAuthor' field.
      * @param value The value of 'firstAuthor'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setFirstAuthor(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.firstAuthor = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'firstAuthor' field has been set.
      * @return True if the 'firstAuthor' field has been set, false otherwise.
      */
    public boolean hasFirstAuthor() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'firstAuthor' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearFirstAuthor() {
      firstAuthor = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'titleId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitleId() {
      return titleId;
    }


    /**
      * Sets the value of the 'titleId' field.
      * @param value The value of 'titleId'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setTitleId(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.titleId = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'titleId' field has been set.
      * @return True if the 'titleId' field has been set, false otherwise.
      */
    public boolean hasTitleId() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'titleId' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearTitleId() {
      titleId = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'embargoInfo' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmbargoInfo() {
      return embargoInfo;
    }


    /**
      * Sets the value of the 'embargoInfo' field.
      * @param value The value of 'embargoInfo'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setEmbargoInfo(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.embargoInfo = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'embargoInfo' field has been set.
      * @return True if the 'embargoInfo' field has been set, false otherwise.
      */
    public boolean hasEmbargoInfo() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'embargoInfo' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearEmbargoInfo() {
      embargoInfo = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'coverageDepth' field.
      * @return The value.
      */
    public java.lang.CharSequence getCoverageDepth() {
      return coverageDepth;
    }


    /**
      * Sets the value of the 'coverageDepth' field.
      * @param value The value of 'coverageDepth'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setCoverageDepth(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.coverageDepth = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'coverageDepth' field has been set.
      * @return True if the 'coverageDepth' field has been set, false otherwise.
      */
    public boolean hasCoverageDepth() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'coverageDepth' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearCoverageDepth() {
      coverageDepth = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'notes' field.
      * @return The value.
      */
    public java.lang.CharSequence getNotes() {
      return notes;
    }


    /**
      * Sets the value of the 'notes' field.
      * @param value The value of 'notes'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setNotes(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.notes = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'notes' field has been set.
      * @return True if the 'notes' field has been set, false otherwise.
      */
    public boolean hasNotes() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'notes' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearNotes() {
      notes = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'publisherName' field.
      * @return The value.
      */
    public java.lang.CharSequence getPublisherName() {
      return publisherName;
    }


    /**
      * Sets the value of the 'publisherName' field.
      * @param value The value of 'publisherName'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setPublisherName(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.publisherName = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'publisherName' field has been set.
      * @return True if the 'publisherName' field has been set, false otherwise.
      */
    public boolean hasPublisherName() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'publisherName' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearPublisherName() {
      publisherName = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'publicationType' field.
      * @return The value.
      */
    public java.lang.CharSequence getPublicationType() {
      return publicationType;
    }


    /**
      * Sets the value of the 'publicationType' field.
      * @param value The value of 'publicationType'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setPublicationType(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.publicationType = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'publicationType' field has been set.
      * @return True if the 'publicationType' field has been set, false otherwise.
      */
    public boolean hasPublicationType() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'publicationType' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearPublicationType() {
      publicationType = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateMonographPublishedPrint' field.
      * @return The value.
      */
    public java.lang.CharSequence getDateMonographPublishedPrint() {
      return dateMonographPublishedPrint;
    }


    /**
      * Sets the value of the 'dateMonographPublishedPrint' field.
      * @param value The value of 'dateMonographPublishedPrint'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setDateMonographPublishedPrint(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.dateMonographPublishedPrint = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'dateMonographPublishedPrint' field has been set.
      * @return True if the 'dateMonographPublishedPrint' field has been set, false otherwise.
      */
    public boolean hasDateMonographPublishedPrint() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'dateMonographPublishedPrint' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearDateMonographPublishedPrint() {
      dateMonographPublishedPrint = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateMonographPublishedOnline' field.
      * @return The value.
      */
    public java.lang.CharSequence getDateMonographPublishedOnline() {
      return dateMonographPublishedOnline;
    }


    /**
      * Sets the value of the 'dateMonographPublishedOnline' field.
      * @param value The value of 'dateMonographPublishedOnline'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setDateMonographPublishedOnline(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.dateMonographPublishedOnline = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'dateMonographPublishedOnline' field has been set.
      * @return True if the 'dateMonographPublishedOnline' field has been set, false otherwise.
      */
    public boolean hasDateMonographPublishedOnline() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'dateMonographPublishedOnline' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearDateMonographPublishedOnline() {
      dateMonographPublishedOnline = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'monographVolume' field.
      * @return The value.
      */
    public java.lang.Integer getMonographVolume() {
      return monographVolume;
    }


    /**
      * Sets the value of the 'monographVolume' field.
      * @param value The value of 'monographVolume'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setMonographVolume(java.lang.Integer value) {
      validate(fields()[22], value);
      this.monographVolume = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'monographVolume' field has been set.
      * @return True if the 'monographVolume' field has been set, false otherwise.
      */
    public boolean hasMonographVolume() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'monographVolume' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearMonographVolume() {
      monographVolume = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'monographEdition' field.
      * @return The value.
      */
    public java.lang.CharSequence getMonographEdition() {
      return monographEdition;
    }


    /**
      * Sets the value of the 'monographEdition' field.
      * @param value The value of 'monographEdition'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setMonographEdition(java.lang.CharSequence value) {
      validate(fields()[23], value);
      this.monographEdition = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'monographEdition' field has been set.
      * @return True if the 'monographEdition' field has been set, false otherwise.
      */
    public boolean hasMonographEdition() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'monographEdition' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearMonographEdition() {
      monographEdition = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstEditor' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstEditor() {
      return firstEditor;
    }


    /**
      * Sets the value of the 'firstEditor' field.
      * @param value The value of 'firstEditor'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setFirstEditor(java.lang.CharSequence value) {
      validate(fields()[24], value);
      this.firstEditor = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'firstEditor' field has been set.
      * @return True if the 'firstEditor' field has been set, false otherwise.
      */
    public boolean hasFirstEditor() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'firstEditor' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearFirstEditor() {
      firstEditor = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'parentPublicationTitleId' field.
      * @return The value.
      */
    public java.lang.CharSequence getParentPublicationTitleId() {
      return parentPublicationTitleId;
    }


    /**
      * Sets the value of the 'parentPublicationTitleId' field.
      * @param value The value of 'parentPublicationTitleId'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setParentPublicationTitleId(java.lang.CharSequence value) {
      validate(fields()[25], value);
      this.parentPublicationTitleId = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'parentPublicationTitleId' field has been set.
      * @return True if the 'parentPublicationTitleId' field has been set, false otherwise.
      */
    public boolean hasParentPublicationTitleId() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'parentPublicationTitleId' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearParentPublicationTitleId() {
      parentPublicationTitleId = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'precedingPublicationTitleId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPrecedingPublicationTitleId() {
      return precedingPublicationTitleId;
    }


    /**
      * Sets the value of the 'precedingPublicationTitleId' field.
      * @param value The value of 'precedingPublicationTitleId'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setPrecedingPublicationTitleId(java.lang.CharSequence value) {
      validate(fields()[26], value);
      this.precedingPublicationTitleId = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'precedingPublicationTitleId' field has been set.
      * @return True if the 'precedingPublicationTitleId' field has been set, false otherwise.
      */
    public boolean hasPrecedingPublicationTitleId() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'precedingPublicationTitleId' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearPrecedingPublicationTitleId() {
      precedingPublicationTitleId = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /**
      * Gets the value of the 'accessType' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccessType() {
      return accessType;
    }


    /**
      * Sets the value of the 'accessType' field.
      * @param value The value of 'accessType'.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder setAccessType(java.lang.CharSequence value) {
      validate(fields()[27], value);
      this.accessType = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /**
      * Checks whether the 'accessType' field has been set.
      * @return True if the 'accessType' field has been set, false otherwise.
      */
    public boolean hasAccessType() {
      return fieldSetFlags()[27];
    }


    /**
      * Clears the value of the 'accessType' field.
      * @return This builder.
      */
    public fr.abes.LigneKbartImprime.Builder clearAccessType() {
      accessType = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LigneKbartImprime build() {
      try {
        LigneKbartImprime record = new LigneKbartImprime();
        record.currentLine = fieldSetFlags()[0] ? this.currentLine : (java.lang.Integer) defaultValue(fields()[0]);
        record.totalLines = fieldSetFlags()[1] ? this.totalLines : (java.lang.Integer) defaultValue(fields()[1]);
        record.ppn = fieldSetFlags()[2] ? this.ppn : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.publicationTitle = fieldSetFlags()[3] ? this.publicationTitle : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.printIdentifier = fieldSetFlags()[4] ? this.printIdentifier : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.onlineIdentifier = fieldSetFlags()[5] ? this.onlineIdentifier : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.dateFirstIssueOnline = fieldSetFlags()[6] ? this.dateFirstIssueOnline : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.numFirstVolOnline = fieldSetFlags()[7] ? this.numFirstVolOnline : (java.lang.Integer) defaultValue(fields()[7]);
        record.numFirstIssueOnline = fieldSetFlags()[8] ? this.numFirstIssueOnline : (java.lang.Integer) defaultValue(fields()[8]);
        record.dateLastIssueOnline = fieldSetFlags()[9] ? this.dateLastIssueOnline : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.numLastVolOnline = fieldSetFlags()[10] ? this.numLastVolOnline : (java.lang.Integer) defaultValue(fields()[10]);
        record.numLastIssueOnline = fieldSetFlags()[11] ? this.numLastIssueOnline : (java.lang.Integer) defaultValue(fields()[11]);
        record.titleUrl = fieldSetFlags()[12] ? this.titleUrl : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.firstAuthor = fieldSetFlags()[13] ? this.firstAuthor : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.titleId = fieldSetFlags()[14] ? this.titleId : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.embargoInfo = fieldSetFlags()[15] ? this.embargoInfo : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.coverageDepth = fieldSetFlags()[16] ? this.coverageDepth : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.notes = fieldSetFlags()[17] ? this.notes : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.publisherName = fieldSetFlags()[18] ? this.publisherName : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.publicationType = fieldSetFlags()[19] ? this.publicationType : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.dateMonographPublishedPrint = fieldSetFlags()[20] ? this.dateMonographPublishedPrint : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.dateMonographPublishedOnline = fieldSetFlags()[21] ? this.dateMonographPublishedOnline : (java.lang.CharSequence) defaultValue(fields()[21]);
        record.monographVolume = fieldSetFlags()[22] ? this.monographVolume : (java.lang.Integer) defaultValue(fields()[22]);
        record.monographEdition = fieldSetFlags()[23] ? this.monographEdition : (java.lang.CharSequence) defaultValue(fields()[23]);
        record.firstEditor = fieldSetFlags()[24] ? this.firstEditor : (java.lang.CharSequence) defaultValue(fields()[24]);
        record.parentPublicationTitleId = fieldSetFlags()[25] ? this.parentPublicationTitleId : (java.lang.CharSequence) defaultValue(fields()[25]);
        record.precedingPublicationTitleId = fieldSetFlags()[26] ? this.precedingPublicationTitleId : (java.lang.CharSequence) defaultValue(fields()[26]);
        record.accessType = fieldSetFlags()[27] ? this.accessType : (java.lang.CharSequence) defaultValue(fields()[27]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LigneKbartImprime>
    WRITER$ = (org.apache.avro.io.DatumWriter<LigneKbartImprime>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LigneKbartImprime>
    READER$ = (org.apache.avro.io.DatumReader<LigneKbartImprime>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.currentLine);

    out.writeInt(this.totalLines);

    out.writeString(this.ppn);

    if (this.publicationTitle == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.publicationTitle);
    }

    if (this.printIdentifier == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.printIdentifier);
    }

    if (this.onlineIdentifier == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.onlineIdentifier);
    }

    if (this.dateFirstIssueOnline == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.dateFirstIssueOnline);
    }

    if (this.numFirstVolOnline == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.numFirstVolOnline);
    }

    if (this.numFirstIssueOnline == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.numFirstIssueOnline);
    }

    if (this.dateLastIssueOnline == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.dateLastIssueOnline);
    }

    if (this.numLastVolOnline == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.numLastVolOnline);
    }

    if (this.numLastIssueOnline == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.numLastIssueOnline);
    }

    if (this.titleUrl == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.titleUrl);
    }

    if (this.firstAuthor == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.firstAuthor);
    }

    if (this.titleId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.titleId);
    }

    if (this.embargoInfo == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.embargoInfo);
    }

    if (this.coverageDepth == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.coverageDepth);
    }

    if (this.notes == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.notes);
    }

    if (this.publisherName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.publisherName);
    }

    if (this.publicationType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.publicationType);
    }

    if (this.dateMonographPublishedPrint == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.dateMonographPublishedPrint);
    }

    if (this.dateMonographPublishedOnline == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.dateMonographPublishedOnline);
    }

    if (this.monographVolume == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.monographVolume);
    }

    if (this.monographEdition == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.monographEdition);
    }

    if (this.firstEditor == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.firstEditor);
    }

    if (this.parentPublicationTitleId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.parentPublicationTitleId);
    }

    if (this.precedingPublicationTitleId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.precedingPublicationTitleId);
    }

    if (this.accessType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.accessType);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.currentLine = in.readInt();

      this.totalLines = in.readInt();

      this.ppn = in.readString(this.ppn instanceof Utf8 ? (Utf8)this.ppn : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.publicationTitle = null;
      } else {
        this.publicationTitle = in.readString(this.publicationTitle instanceof Utf8 ? (Utf8)this.publicationTitle : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.printIdentifier = null;
      } else {
        this.printIdentifier = in.readString(this.printIdentifier instanceof Utf8 ? (Utf8)this.printIdentifier : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.onlineIdentifier = null;
      } else {
        this.onlineIdentifier = in.readString(this.onlineIdentifier instanceof Utf8 ? (Utf8)this.onlineIdentifier : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.dateFirstIssueOnline = null;
      } else {
        this.dateFirstIssueOnline = in.readString(this.dateFirstIssueOnline instanceof Utf8 ? (Utf8)this.dateFirstIssueOnline : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.numFirstVolOnline = null;
      } else {
        this.numFirstVolOnline = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.numFirstIssueOnline = null;
      } else {
        this.numFirstIssueOnline = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.dateLastIssueOnline = null;
      } else {
        this.dateLastIssueOnline = in.readString(this.dateLastIssueOnline instanceof Utf8 ? (Utf8)this.dateLastIssueOnline : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.numLastVolOnline = null;
      } else {
        this.numLastVolOnline = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.numLastIssueOnline = null;
      } else {
        this.numLastIssueOnline = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.titleUrl = null;
      } else {
        this.titleUrl = in.readString(this.titleUrl instanceof Utf8 ? (Utf8)this.titleUrl : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.firstAuthor = null;
      } else {
        this.firstAuthor = in.readString(this.firstAuthor instanceof Utf8 ? (Utf8)this.firstAuthor : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.titleId = null;
      } else {
        this.titleId = in.readString(this.titleId instanceof Utf8 ? (Utf8)this.titleId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.embargoInfo = null;
      } else {
        this.embargoInfo = in.readString(this.embargoInfo instanceof Utf8 ? (Utf8)this.embargoInfo : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.coverageDepth = null;
      } else {
        this.coverageDepth = in.readString(this.coverageDepth instanceof Utf8 ? (Utf8)this.coverageDepth : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.notes = null;
      } else {
        this.notes = in.readString(this.notes instanceof Utf8 ? (Utf8)this.notes : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.publisherName = null;
      } else {
        this.publisherName = in.readString(this.publisherName instanceof Utf8 ? (Utf8)this.publisherName : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.publicationType = null;
      } else {
        this.publicationType = in.readString(this.publicationType instanceof Utf8 ? (Utf8)this.publicationType : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.dateMonographPublishedPrint = null;
      } else {
        this.dateMonographPublishedPrint = in.readString(this.dateMonographPublishedPrint instanceof Utf8 ? (Utf8)this.dateMonographPublishedPrint : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.dateMonographPublishedOnline = null;
      } else {
        this.dateMonographPublishedOnline = in.readString(this.dateMonographPublishedOnline instanceof Utf8 ? (Utf8)this.dateMonographPublishedOnline : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.monographVolume = null;
      } else {
        this.monographVolume = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.monographEdition = null;
      } else {
        this.monographEdition = in.readString(this.monographEdition instanceof Utf8 ? (Utf8)this.monographEdition : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.firstEditor = null;
      } else {
        this.firstEditor = in.readString(this.firstEditor instanceof Utf8 ? (Utf8)this.firstEditor : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.parentPublicationTitleId = null;
      } else {
        this.parentPublicationTitleId = in.readString(this.parentPublicationTitleId instanceof Utf8 ? (Utf8)this.parentPublicationTitleId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.precedingPublicationTitleId = null;
      } else {
        this.precedingPublicationTitleId = in.readString(this.precedingPublicationTitleId instanceof Utf8 ? (Utf8)this.precedingPublicationTitleId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.accessType = null;
      } else {
        this.accessType = in.readString(this.accessType instanceof Utf8 ? (Utf8)this.accessType : null);
      }

    } else {
      for (int i = 0; i < 28; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.currentLine = in.readInt();
          break;

        case 1:
          this.totalLines = in.readInt();
          break;

        case 2:
          this.ppn = in.readString(this.ppn instanceof Utf8 ? (Utf8)this.ppn : null);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.publicationTitle = null;
          } else {
            this.publicationTitle = in.readString(this.publicationTitle instanceof Utf8 ? (Utf8)this.publicationTitle : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.printIdentifier = null;
          } else {
            this.printIdentifier = in.readString(this.printIdentifier instanceof Utf8 ? (Utf8)this.printIdentifier : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.onlineIdentifier = null;
          } else {
            this.onlineIdentifier = in.readString(this.onlineIdentifier instanceof Utf8 ? (Utf8)this.onlineIdentifier : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dateFirstIssueOnline = null;
          } else {
            this.dateFirstIssueOnline = in.readString(this.dateFirstIssueOnline instanceof Utf8 ? (Utf8)this.dateFirstIssueOnline : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.numFirstVolOnline = null;
          } else {
            this.numFirstVolOnline = in.readInt();
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.numFirstIssueOnline = null;
          } else {
            this.numFirstIssueOnline = in.readInt();
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dateLastIssueOnline = null;
          } else {
            this.dateLastIssueOnline = in.readString(this.dateLastIssueOnline instanceof Utf8 ? (Utf8)this.dateLastIssueOnline : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.numLastVolOnline = null;
          } else {
            this.numLastVolOnline = in.readInt();
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.numLastIssueOnline = null;
          } else {
            this.numLastIssueOnline = in.readInt();
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.titleUrl = null;
          } else {
            this.titleUrl = in.readString(this.titleUrl instanceof Utf8 ? (Utf8)this.titleUrl : null);
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.firstAuthor = null;
          } else {
            this.firstAuthor = in.readString(this.firstAuthor instanceof Utf8 ? (Utf8)this.firstAuthor : null);
          }
          break;

        case 14:
          if (in.readIndex() != 1) {
            in.readNull();
            this.titleId = null;
          } else {
            this.titleId = in.readString(this.titleId instanceof Utf8 ? (Utf8)this.titleId : null);
          }
          break;

        case 15:
          if (in.readIndex() != 1) {
            in.readNull();
            this.embargoInfo = null;
          } else {
            this.embargoInfo = in.readString(this.embargoInfo instanceof Utf8 ? (Utf8)this.embargoInfo : null);
          }
          break;

        case 16:
          if (in.readIndex() != 1) {
            in.readNull();
            this.coverageDepth = null;
          } else {
            this.coverageDepth = in.readString(this.coverageDepth instanceof Utf8 ? (Utf8)this.coverageDepth : null);
          }
          break;

        case 17:
          if (in.readIndex() != 1) {
            in.readNull();
            this.notes = null;
          } else {
            this.notes = in.readString(this.notes instanceof Utf8 ? (Utf8)this.notes : null);
          }
          break;

        case 18:
          if (in.readIndex() != 1) {
            in.readNull();
            this.publisherName = null;
          } else {
            this.publisherName = in.readString(this.publisherName instanceof Utf8 ? (Utf8)this.publisherName : null);
          }
          break;

        case 19:
          if (in.readIndex() != 1) {
            in.readNull();
            this.publicationType = null;
          } else {
            this.publicationType = in.readString(this.publicationType instanceof Utf8 ? (Utf8)this.publicationType : null);
          }
          break;

        case 20:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dateMonographPublishedPrint = null;
          } else {
            this.dateMonographPublishedPrint = in.readString(this.dateMonographPublishedPrint instanceof Utf8 ? (Utf8)this.dateMonographPublishedPrint : null);
          }
          break;

        case 21:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dateMonographPublishedOnline = null;
          } else {
            this.dateMonographPublishedOnline = in.readString(this.dateMonographPublishedOnline instanceof Utf8 ? (Utf8)this.dateMonographPublishedOnline : null);
          }
          break;

        case 22:
          if (in.readIndex() != 1) {
            in.readNull();
            this.monographVolume = null;
          } else {
            this.monographVolume = in.readInt();
          }
          break;

        case 23:
          if (in.readIndex() != 1) {
            in.readNull();
            this.monographEdition = null;
          } else {
            this.monographEdition = in.readString(this.monographEdition instanceof Utf8 ? (Utf8)this.monographEdition : null);
          }
          break;

        case 24:
          if (in.readIndex() != 1) {
            in.readNull();
            this.firstEditor = null;
          } else {
            this.firstEditor = in.readString(this.firstEditor instanceof Utf8 ? (Utf8)this.firstEditor : null);
          }
          break;

        case 25:
          if (in.readIndex() != 1) {
            in.readNull();
            this.parentPublicationTitleId = null;
          } else {
            this.parentPublicationTitleId = in.readString(this.parentPublicationTitleId instanceof Utf8 ? (Utf8)this.parentPublicationTitleId : null);
          }
          break;

        case 26:
          if (in.readIndex() != 1) {
            in.readNull();
            this.precedingPublicationTitleId = null;
          } else {
            this.precedingPublicationTitleId = in.readString(this.precedingPublicationTitleId instanceof Utf8 ? (Utf8)this.precedingPublicationTitleId : null);
          }
          break;

        case 27:
          if (in.readIndex() != 1) {
            in.readNull();
            this.accessType = null;
          } else {
            this.accessType = in.readString(this.accessType instanceof Utf8 ? (Utf8)this.accessType : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










